### ISSUE TITLE
contoml.loads(contoml.dumps(data)) does not work

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/python-consistent-toml#13]
```
In [16]: data
Out[16]: 
{'description': u'',
 'emails': [u'adnan@incubaid.com',
  u'fatayera@incubaid.com',
  u'adnan.fatayerji@incubaid.com',
  u'adnan@greenitglobe.com',
  u'fatayera@greenitglobe.com',
  u'adnan.fatayerji@greenitglobe.com'],
 'firstname': u'adnan',
 'git_aydo': u'',
 'git_github': u'',
 'groups': [u'sales', u'dubai', u'mgmt'],
 'id': u'fatayera',
 'lastname': u'fatayerji',
 'mobiles': [u'971507192009'],
 'skype': u'',
 'telegram': u'971507192009'}

In [17]: c= contoml.loads(contoml.dumps(data))

In [18]: print c.primitive
{'': {'description': u'', 'firstname': u'adnan', 'telegram': u'971507192009', 'skype': u'', 'git_aydo': u'', 'id': u'fatayera', 'git_github': u'', 'groups': [u'sales', u'dubai', u'mgmt'], 'lastname': u'fatayerji', 'emails': [u'adnan@incubaid.com', u'fatayera@incubaid.com', u'adnan.fatayerji@incubaid.com', u'adnan@greenitglobe.com', u'fatayera@greenitglobe.com', u'adnan.fatayerji@greenitglobe.com'], 'mobiles': [u'971507192009']}}
```

as you ca see the c.primitive is not same as original

to make it easy for you the data set in json
```
json.dumps(data)
Out[20]: '{"telegram": "971507192009", "description": "", "firstname": "adnan", "lastname": "fatayerji", "git_aydo": "", "emails": ["adnan@incubaid.com", "fatayera@incubaid.com", "adnan.fatayerji@incubaid.com", "adnan@greenitglobe.com", "fatayera@greenitglobe.com", "adnan.fatayerji@greenitglobe.com"], "git_github": "", "groups": ["sales", "dubai", "mgmt"], "skype": "", "id": "fatayera", "mobiles": ["971507192009"]}'
```

**Comment by amrhassan** [comment]
The anonymous table is actually intentionally labeled with an empty string throughout the API to differentiate it from the other named tables.

Out of convenience I can have the conversion to primitive data structure (the `.primitive` property) collapse the anonymous table onto the top-level dict. But it wouldn't be consistent with the way you would access the object returned from `load()` and `loads()`.

Are you only going to use the top-level package API for parsing and pretty-printing out TOML or at some point do you expect to manipulate the TOML file data manually?

**Comment by despiegk** [comment]
its mainly a serializer/deserializer
why are we all doing so difficult

a python dict -> nicely formatted toml
toml -> python dict

thats it
nothing complex, I really don't get all the over complication on this library

contoml.loads(contoml.dumps(data))
should ofcourse result in same data 

try the following test
```
import contoml
import json
data=json.loads('{"telegram": "971507192009", "description": "", "firstname": "adnan", "lastname": "fatayerji", "git_aydo": "", "emails": ["adnan@incubaid.com", "fatayera@incubaid.com", "adnan.fatayerji@incubaid.com", "adnan@greenitglobe.com", "fatayera@greenitglobe.com", "adnan.fatayerji@greenitglobe.com"], "git_github": "", "groups": ["sales", "dubai", "mgmt"], "skype": "", "id": "fatayera", "mobiles": ["971507192009"]}'

txt=contoml.dumps(data)
data2=contoml.loads(txt)
txt2=contoml.dumps(data2)
assert txt==txt2

```

**Comment by amrhassan** [comment]
Please note that this invariant will not hold if the original data contains a `None`/`null` since it's now serialized to an empty string in TOML which will be unserialized back into a string type, not a Python `None`.
