### ISSUE TITLE
Nested tables don't work in side array of tables

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/python-consistent-toml#22]
In [1]: import contoml

In [2]: toml = contoml.new()

In [3]: toml['test']=[{'address': 1234, 'tls': {'key':'test key', 'crt':'test crt'}}]                                                                                   

In [4]: print toml.dumps()
[[test]]
crt = "test crt"
key = "test key"
address = 1234

**Comment by amrhassan** [comment]
Fixed in 4166ccdd06b35ffda84b5aa9a47968da55b05abb
