### ISSUE TITLE
Should not create inline tables when setting whole dicts as values

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/python-consistent-toml#23]
In [5]: toml = contoml.new()

In [6]: toml['test']=[{'address': 1234, 'tls': [{'key':'test key', 'crt':'test crt'}]}]

In [7]: print toml.dum
toml.dump   toml.dumps  

In [7]: print toml.dumps()
[[test]]
tls = [{crt = "test crt", key = "test key"}]
address = 1234

**Comment by amrhassan** [comment]
Was this on v0.32?

**Comment by amrhassan** [comment]
contoml has been stripped back down to its original purpose - which is to update pre-written TOML files without messing up their formatting. Support for constructing new sections/entries is currently dropped. Please use another Python module for your TOML serialization needs (like [pytoml](https://github.com/avakar/pytoml)).

The TOML formatting features have been moved to the project [prettytoml](https://github.com/Jumpscale/python-pretty-toml). Feel free to report any issues about the latter project on its issue tracker.

**Comment by despiegk** [comment]
are you kidding me
the original goal
was

dict to nicely formatted toml
always same formatted



k.

On Sun, Oct 25, 2015 at 11:26 AM, Amr Hassan <notifications@github.com>
wrote:

> contoml has been stripped back down to its original purpose - which is to
> update pre-written TOML files without messing up their formatting. Support
> for constructing new sections/entries is currently dropped. Please use
> another Python module for your TOML serialization needs (like pytoml
> <https://github.com/avakar/pytoml>).
>
> The TOML formatting features have been moved to the project prettytoml
> <https://github.com/Jumpscale/python-pretty-toml>. Feel free to report
> any issues about the latter project on its issue tracker.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/python-consistent-toml/issues/23#issuecomment-150898516>
> .
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk
