### ISSUE TITLE
how to get to a std python data structure

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/python-consistent-toml#6]
is not in docs
now we get something like
[[], [50-bare_string: id], [], [0-assignment: =], [], [90-string: "len"], [], [91-newline: 
], [], [50-bare_string: name], [], [0-assignment: =], [], [90-string: "ms1_lenoir"], [], [91-newline: 
], [], [50-bare_string: descr], [], [0-assignment: =], [], [90-string: ""], [], [91-newline: 
], [91-newline: 
]]

not very nice

why do you keep the newlines ...

I thought the goal of this project was to go from any python data structure & serialize in a consistent way
which means this info does not have to be remembered

I am surprised that something like
data=contoml.loads(C) 
does not result in a clean python dict of lists....

**Comment by despiegk** [comment]
the easiest fix is prob to create a method which can dump such a data structure

**Comment by grimpy** [comment]
The reason for all of this is so we can keep the original structure of the toml file including comments and new lines.

If you want python dict/list structure use TOMLFile.primitive

example

```

In [20]: tom = contoml.loads("""
[apple]
color = green
type = jonagold
""")
In [21]: tom.primitive
Out[21]: {'apple': {'color': 'green', 'type': 'jonagold'}}

```

**Comment by amrhassan** [comment]
As @grimpy elaborated, the types constructed by the `contoml` are suped up equivalents of Python's containers and primitives. You can index and update them like regular Python values and they'll do their best to maintain their original textual structure when serialized back.

Perhaps the `__repr__()` definitions of those types aren't very clear, but they're supposed to show the content of those objects which are the lexcial tokens that made up this value.

The constructed top-level value is an instance of `TOMLFile` and its docstrings reveal the property that can be used to go from this data structure to a plain Python container:
```
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 | 
 |  primitive
 |      Returns a primitive object representation for this container (which is a dict).
 |      
 |      WARNING: The returned container does not contain any markup or formatting metadata.
```

Please close this issue if this answers your question.

**Comment by despiegk** [comment]
the idea was NOT to keep enter's, spaces, ...
the full goal of this module is to always generate same serialization independent of what people put in like in HRD

**Comment by despiegk** [comment]
tom.primitive
works (-:
great, will have to document this

**Comment by amrhassan** [comment]
I've added an example to the `README.md` file displayed on the main page which mentions that exact use case.
