### ISSUE TITLE
Consistent pretty-printing feature

### ISSUE THREAD

**Issue by amrhassan** [Jumpscale/python-consistent-toml#8]
As a user of the module I should be able to format my pre-existing TOML files into a consistent pretty format.

The consistent output format rules should include:
* Every key and value pair in any table should be separated the triplet (single space character, an assignment character `=`, single space character).
* Anonymous table should never be indented.
* Nth-level table sections should be indented by `(N-1)*2` spaces.
* Line-terminating comments should always be prefixed by a single tab character whitespace only.
* Lines whose lengths exceed `120` characters whose values are strings, arrays, or inline tables should have the array or string value broken onto multiple lines and the inline table turned into a multiline table section so as to try to maintain a maximum line length of `120`.
* Tables should always be separated by an empty newline.

**Comment by amrhassan** [comment]
@grimpy, @rkhamis, @despiegk 
I can't seem to find an "official" style guideline for TOML, so please feel free to review and contribute to the list I've written down.

**Comment by rkhamis** [comment]
These rules could be used to get toml as readable as possible:

- Sections/tables should be separated by a couple of lines for readability.
- With inline comments, the hash must be preceded and followed by a single
white space.
- If an inline table is longer than 120 characters, we turn it into a
standard table with each element on a separate line.

@grimpy <https://github.com/grimpy>, @rkhamis <https://github.com/rkhamis>,
@despiegk <https://github.com/despiegk>
I can't seem to find an "official" style guideline for TOML, so please feel
free to review and contribute to the list I've written down.

—
Reply to this email directly or view it on GitHub
<https://github.com/Jumpscale/python-consistent-toml/issues/8#issuecomment-124217969>
.

**Comment by amrhassan** [comment]
@rkhamis The inline comment rule was already listed. I've worked the other two suggested rules into the requirements.
